* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_bsearch	IMPORT
_cmpdww	IMPORT
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enable_printf_float	IMPORT
_exit	IMPORT
_isalnum	IMPORT
_isalpha	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_itoa10	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_qsort	IMPORT
_rand	IMPORT
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_strcspn	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strpbrk	IMPORT
_strrchr	IMPORT
_strspn	IMPORT
_strstr	IMPORT
_strtok	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_utoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_zerodw	IMPORT
__FinishIntegerToASCII	EXPORT


*******************************************************************************

* FUNCTION _FinishIntegerToASCII(): defined at _FinishIntegerToASCII.c:10
__FinishIntegerToASCII	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: firstDigit: char *: line 10
*      6,U:    2 bytes: endOfString: char *: line 10
*      8,U:    2 bytes: returnValue: char *: line 10
* Line _FinishIntegerToASCII.c:27: inline assembly
* Inline assembly:


        pshs y ; preserve CMOC globals pointer
        ldx 4,U
        ldy 6,U ; cannot refer to globals now
        clr ,y
        leay -1,y
        bra @loopCond
@loopBody
; Swap *firstDigit and *endOfString.
        lda ,x
        ldb ,y
        sta ,y
        stb ,x+ ; also increment firstDigit
        leay -1,y ; --endOfString
@loopCond
        sty 6,U ; store for comparison
        cmpx 6,U ; firstDigit < endOfString ?
        blo @loopBody
        puls y
    

* End of inline assembly.
* Line _FinishIntegerToASCII.c:50: return with value
	LDD	8,U		variable `returnValue', declared at _FinishIntegerToASCII.c:10
* optim: branchToNextLocation
* Useless label L00077 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION _FinishIntegerToASCII(): defined at _FinishIntegerToASCII.c:10
funcend__FinishIntegerToASCII	EQU *
funcsize__FinishIntegerToASCII	EQU	funcend__FinishIntegerToASCII-__FinishIntegerToASCII


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END
