* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


_divmod16	EXPORT


*******************************************************************************

* FUNCTION divmod16(): defined at divmod16.c:2
_divmod16	EQU	*
* Assembly-only function.
* Line divmod16.c:5: inline assembly
* Inline assembly:


DIV16 IMPORT
        ldx 2,s ; dividend
        ldd 4,s ; divisor
        lbsr DIV16
        stx [6,s] ; quotient
        std [8,s] ; remainer
    

* End of inline assembly.
* Useless label L00001 removed
	RTS
* END FUNCTION divmod16(): defined at divmod16.c:2
funcend_divmod16	EQU *
funcsize_divmod16	EQU	funcend_divmod16-_divmod16


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END
