* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_bsearch	IMPORT
_cmpdww	IMPORT
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enable_printf_float	IMPORT
_exit	IMPORT
_isalnum	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_itoa10	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_qsort	IMPORT
_rand	IMPORT
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_strcspn	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strpbrk	IMPORT
_strrchr	IMPORT
_strspn	IMPORT
_strstr	IMPORT
_strtok	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_utoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_zerodw	IMPORT
_isalpha	EXPORT


*******************************************************************************

* FUNCTION isalpha(): defined at isalpha.c:5
_isalpha	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: c: int: line 5
* Line isalpha.c:7: return with value
	LDD	4,U		variable c
	CMPD	#$41
	BGE	L00081		if true
	CLRB
	BRA	L00082		false
L00081	EQU	*
	LDB	#1
L00082	EQU	*
	TSTB			&&
	BEQ	L00080		&& at isalpha.c:7 yields false, B == 0
	LDD	4,U		variable c
	CMPD	#$5A
	BLE	L00083		if true
	CLRB
	BRA	L00084		false
L00083	EQU	*
	LDB	#1
L00084	EQU	*
	TSTB			&&
	BEQ	L00080		&& at isalpha.c:7 yields false, B == 0
	LDB	#1		&& yields true
L00080	EQU	*
	TSTB			||
	BNE	L00078		|| yields true
	LDD	4,U		variable c
	CMPD	#$61
	BGE	L00086		if true
	CLRB
	BRA	L00087		false
L00086	EQU	*
	LDB	#1
L00087	EQU	*
	TSTB			&&
	BEQ	L00085		&& at isalpha.c:7 yields false, B == 0
	LDD	4,U		variable c
	CMPD	#$7A
	BLE	L00088		if true
	CLRB
	BRA	L00089		false
L00088	EQU	*
	LDB	#1
L00089	EQU	*
	TSTB			&&
	BEQ	L00085		&& at isalpha.c:7 yields false, B == 0
	LDB	#1		&& yields true
L00085	EQU	*
	TSTB			||
	BEQ	L00079
L00078	EQU	*		|| at isalpha.c:7 yields true, B != 0
L00079	EQU	*
	CLRA			cast from byte
* optim: branchToNextLocation
* Useless label L00077 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION isalpha(): defined at isalpha.c:5
funcend_isalpha	EQU *
funcsize_isalpha	EQU	funcend_isalpha-_isalpha


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END
