* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_bsearch	IMPORT
_cmpdww	IMPORT
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enable_printf_float	IMPORT
_exit	IMPORT
_isalnum	IMPORT
_isalpha	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_qsort	IMPORT
_rand	IMPORT
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_strcspn	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strpbrk	IMPORT
_strrchr	IMPORT
_strspn	IMPORT
_strstr	IMPORT
_strtok	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_utoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_zerodw	IMPORT
_itoa10	EXPORT


*******************************************************************************

* FUNCTION itoa10(): defined at itoa.c:10
_itoa10	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-4,S
* Formal parameter(s):
*      4,U:    2 bytes: value: int: line 10
*      6,U:    2 bytes: str: char *: line 10
* Local non-static variable(s):
*     -4,U:    2 bytes: writer: char *: line 12
*     -2,U:    2 bytes: u: unsigned int: line 15
* Line itoa.c:12: init of variable writer
	LDD	6,U		variable `str', declared at itoa.c:10
	STD	-4,U		variable writer
* Line itoa.c:16: if
	LDD	4,U		variable value
	ADDD	#0
	BGE	L00079		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00078 removed
* Line itoa.c:17
* Line itoa.c:18: assignment: =
	LDX	-4,U		variable writer
	LDB	#$2D
	STB	,X+		post-increment
	STX	-4,U
* Line itoa.c:19: assignment: =
	CLRA			Negation of variable value
	CLRB
	SUBD	4,U
	STD	-2,U
	BRA	L00080		jump over else clause
L00079	EQU	*		else clause of if() started at itoa.c:16
* Line itoa.c:22
* Line itoa.c:22: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	4,U
	STD	-2,U
L00080	EQU	*		end of if() started at itoa.c:16
* Line itoa.c:24: function call: utoa10()
	LDD	-4,U		variable `writer', declared at itoa.c:12
	PSHS	B,A		argument 2 of utoa10(): char *
	LDD	-2,U		variable `u', declared at itoa.c:15
	PSHS	B,A		argument 1 of utoa10(): unsigned int
	LBSR	_utoa10
	LEAS	4,S
* Line itoa.c:25: return with value
	LDD	6,U		variable `str', declared at itoa.c:10
* optim: branchToNextLocation
* Useless label L00077 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION itoa10(): defined at itoa.c:10
funcend_itoa10	EQU *
funcsize_itoa10	EQU	funcend_itoa10-_itoa10


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 1 utility routine(s).
_utoa10	IMPORT


*******************************************************************************

	END
