* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_bsearch	IMPORT
_cmpdww	IMPORT
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enable_printf_float	IMPORT
_exit	IMPORT
_isalnum	IMPORT
_isalpha	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_itoa10	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_rand	IMPORT
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_strcspn	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strpbrk	IMPORT
_strrchr	IMPORT
_strspn	IMPORT
_strstr	IMPORT
_strtok	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_utoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_zerodw	IMPORT


*******************************************************************************

* FUNCTION qsort_swap(): defined at qsort.c:19
_qsort_swap	EQU	*
.static.function.qsort_swap	EQU	*
* Assembly-only function.
* Line qsort.c:22: inline assembly
* Inline assembly:


        pshs u,y
        ldx 6,s ; a
        ldu 8,s ; b
        ldy 10,s ; len (assumed > 0)
@loop
        lda ,x
        ldb ,u
        stb ,x+
        sta ,u+
        leay -1,y
        bne @loop
        puls y,u,pc
    

* End of inline assembly.
* Useless label L00077 removed
* END FUNCTION qsort_swap(): defined at qsort.c:19
funcend_qsort_swap	EQU *
funcsize_qsort_swap	EQU	funcend_qsort_swap-_qsort_swap


*******************************************************************************

* FUNCTION qsort_partition(): defined at qsort.c:44
_qsort_partition	EQU	*
.static.function.qsort_partition	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-10,S
* Formal parameter(s):
*      4,U:    2 bytes: array: char *: line 44
*      6,U:    2 bytes: elemSize: unsigned int: line 44
*      8,U:    2 bytes: comparator: int (*)(const void *, const void *): line 44
*     10,U:    2 bytes: l: unsigned int: line 44
*     12,U:    2 bytes: h: unsigned int: line 44
* Local non-static variable(s):
*    -10,U:    2 bytes: y: char *: line 52
*     -8,U:    2 bytes: res: int: line 53
*     -6,U:    2 bytes: j: unsigned int: line 50
*     -4,U:    2 bytes: x: char *: line 46
*     -2,U:    2 bytes: i: unsigned int: line 47
* Line qsort.c:46: init of variable x
	LDX	12,U		left
	LDD	6,U		right
	LBSR	MUL16
	ADDD	4,U		optim: pushDLoadAdd
* 
* 
	STD	-4,U		variable x
* Line qsort.c:47: init of variable i
	LDD	10,U		variable l
	ADDD	#$FFFF		65535
	STD	-2,U		variable i
* Line qsort.c:50: for init
* Line qsort.c:50: init of variable j
	LDD	10,U		variable `l', declared at qsort.c:44
	STD	-6,U		variable j
	BRA	L00082		jump to for condition
L00081	EQU	*
* Line qsort.c:51: for body
* Line qsort.c:52: init of variable y
	LDX	-6,U		left
	LDD	6,U		right
	LBSR	MUL16
	ADDD	4,U		optim: pushDLoadAdd
* 
* 
	STD	-10,U		variable y
* Line qsort.c:53: init of variable res
* Line qsort.c:53: function call through pointer
	LDD	-4,U		variable `x', declared at qsort.c:46
	PSHS	B,A		argument 2: char *
	LDD	-10,U		variable `y', declared at qsort.c:52
	PSHS	B,A		argument 1: char *
	JSR	[8,U]		indirect call through variable `comparator'
	LEAS	4,S
	STD	-8,U		variable res
* Line qsort.c:55: if
* optim: storeLoad
	ADDD	#0
	BGT	L00086		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00085 removed
* Line qsort.c:56
* Line qsort.c:57: pre-increment
	LDX	-2,U		variable `i', declared at qsort.c:57
	LEAX	1,X
	STX	-2,U
* Line qsort.c:59: function call: qsort_swap()
	LDD	6,U		variable `elemSize', declared at qsort.c:44
	PSHS	B,A		argument 3 of qsort_swap(): unsigned int
	LDD	-10,U		variable `y', declared at qsort.c:52
	PSHS	B,A		argument 2 of qsort_swap(): char *
* optim: removeUselessLdx
	LDD	6,U		right
	LBSR	MUL16
	ADDD	4,U		optim: pushDLoadAdd
* 
* 
	PSHS	B,A		argument 1 of qsort_swap(): char *
	LBSR	_qsort_swap
	LEAS	6,S
L00086	EQU	*		else clause of if() started at qsort.c:55
* Useless label L00087 removed
* Useless label L00083 removed
* Line qsort.c:50: for increment(s)
	LDD	-6,U
	ADDD	#1
	STD	-6,U
L00082	EQU	*
* Line qsort.c:50: for condition
	LDD	-6,U		variable j
	CMPD	12,U		variable h
	BLO	L00081
* optim: branchToNextLocation
* Useless label L00084 removed
* Line qsort.c:64: function call: qsort_swap()
	LDD	6,U		variable `elemSize', declared at qsort.c:44
	PSHS	B,A		argument 3 of qsort_swap(): unsigned int
	LDX	12,U		left
	LDD	6,U		right
	LBSR	MUL16
	ADDD	4,U		optim: pushDLoadAdd
* 
* 
	PSHS	B,A		argument 2 of qsort_swap(): char *
	LDD	-2,U		variable i
	ADDD	#$01		1
	TFR	D,X		optim: stripExtraPulsX
	LDD	6,U		variable `elemSize', declared at qsort.c:44
* optim: stripExtraPulsX
	LBSR	MUL16
	ADDD	4,U		optim: pushDLoadAdd
* 
* 
	PSHS	B,A		argument 1 of qsort_swap(): char *
	LBSR	_qsort_swap
	LEAS	6,S
* Line qsort.c:65: return with value
	LDD	-2,U		variable i
	ADDD	#$01		1
* optim: branchToNextLocation
* Useless label L00078 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION qsort_partition(): defined at qsort.c:44
funcend_qsort_partition	EQU *
funcsize_qsort_partition	EQU	funcend_qsort_partition-_qsort_partition


*******************************************************************************

* FUNCTION qsort_work(): defined at qsort.c:70
_qsort_work	EQU	*
.static.function.qsort_work	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Formal parameter(s):
*      4,U:    2 bytes: array: char *: line 70
*      6,U:    2 bytes: elemSize: unsigned int: line 70
*      8,U:    2 bytes: comparator: int (*)(const void *, const void *): line 70
*     10,U:    2 bytes: l: unsigned int: line 70
*     12,U:    2 bytes: h: unsigned int: line 70
* Local non-static variable(s):
*     -2,U:    2 bytes: p: unsigned int: line 76
* Line qsort.c:74: if
	LDD	10,U		variable l
	CMPD	12,U		variable h
	LBHS	L00089		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00088 removed
* Line qsort.c:75
* Line qsort.c:76: init of variable p
* Line qsort.c:76: function call: qsort_partition()
	LDD	12,U		variable `h', declared at qsort.c:70
	PSHS	B,A		argument 5 of qsort_partition(): unsigned int
	LDD	10,U		variable `l', declared at qsort.c:70
	PSHS	B,A		argument 4 of qsort_partition(): unsigned int
	LDD	8,U		variable `comparator', declared at qsort.c:70
	PSHS	B,A		argument 3 of qsort_partition(): int (*)(const void *, const void *)
	LDD	6,U		variable `elemSize', declared at qsort.c:70
	PSHS	B,A		argument 2 of qsort_partition(): unsigned int
	LDD	4,U		variable `array', declared at qsort.c:70
	PSHS	B,A		argument 1 of qsort_partition(): char *
	LBSR	_qsort_partition
	LEAS	10,S
	STD	-2,U		variable p
* Line qsort.c:78: if
* optim: storeLoad
	ADDD	#0
	BLS	L00091		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00090 removed
* Line qsort.c:79
* Line qsort.c:79: function call: qsort_work()
	LDD	-2,U		variable p
	ADDD	#$FFFF		65535
	PSHS	B,A		argument 5 of qsort_work(): unsigned int
	LDD	10,U		variable `l', declared at qsort.c:70
	PSHS	B,A		argument 4 of qsort_work(): unsigned int
	LDD	8,U		variable `comparator', declared at qsort.c:70
	PSHS	B,A		argument 3 of qsort_work(): int (*)(const void *, const void *)
	LDD	6,U		variable `elemSize', declared at qsort.c:70
	PSHS	B,A		argument 2 of qsort_work(): unsigned int
	LDD	4,U		variable `array', declared at qsort.c:70
	PSHS	B,A		argument 1 of qsort_work(): char *
	BSR	_qsort_work
	LEAS	10,S
L00091	EQU	*		else clause of if() started at qsort.c:78
* Useless label L00092 removed
* Line qsort.c:80: function call: qsort_work()
	LDD	12,U		variable `h', declared at qsort.c:70
	PSHS	B,A		argument 5 of qsort_work(): unsigned int
	LDD	-2,U		variable p
	ADDD	#$01		1
	PSHS	B,A		argument 4 of qsort_work(): unsigned int
	LDD	8,U		variable `comparator', declared at qsort.c:70
	PSHS	B,A		argument 3 of qsort_work(): int (*)(const void *, const void *)
	LDD	6,U		variable `elemSize', declared at qsort.c:70
	PSHS	B,A		argument 2 of qsort_work(): unsigned int
	LDD	4,U		variable `array', declared at qsort.c:70
	PSHS	B,A		argument 1 of qsort_work(): char *
	LBSR	_qsort_work
	LEAS	10,S
L00089	EQU	*		else clause of if() started at qsort.c:74
* Useless label L00093 removed
* Useless label L00079 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION qsort_work(): defined at qsort.c:70
funcend_qsort_work	EQU *
funcsize_qsort_work	EQU	funcend_qsort_work-_qsort_work
_qsort	EXPORT


*******************************************************************************

* FUNCTION qsort(): defined at qsort.c:86
_qsort	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: base: void *: line 86
*      6,U:    2 bytes: nmemb: unsigned int: line 86
*      8,U:    2 bytes: size: unsigned int: line 86
*     10,U:    2 bytes: compar: int (*)(const void *, const void *): line 86
* Line qsort.c:88: if
	LDD	6,U		variable nmemb
	CMPD	#$01
	BLS	L00095		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00096 removed
	LDD	8,U		variable size
* optim: removeCMPZeroAfterLDIfBHI (BHI->BNE)
	BEQ	L00095		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00094 removed
* Line qsort.c:89
* Line qsort.c:89: function call: qsort_work()
	LDD	6,U		variable nmemb
	ADDD	#$FFFF		65535
	PSHS	B,A		argument 5 of qsort_work(): unsigned int
	CLRA
	CLRB
	PSHS	B,A		argument 4 of qsort_work(): int
	LDD	10,U		variable `compar', declared at qsort.c:86
	PSHS	B,A		argument 3 of qsort_work(): int (*)(const void *, const void *)
	LDD	8,U		variable `size', declared at qsort.c:86
	PSHS	B,A		argument 2 of qsort_work(): unsigned int
	LDD	4,U		variable `base', declared at qsort.c:86
* Emitted no code to cast `void *' to `char *'
	PSHS	B,A		argument 1 of qsort_work(): char *
	LBSR	_qsort_work
	LEAS	10,S
L00095	EQU	*		else clause of if() started at qsort.c:88
* Useless label L00097 removed
* Useless label L00080 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION qsort(): defined at qsort.c:86
funcend_qsort	EQU *
funcsize_qsort	EQU	funcend_qsort-_qsort


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 1 utility routine(s).
MUL16	IMPORT


*******************************************************************************

	END
