* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_bsearch	IMPORT
_cmpdww	IMPORT
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enable_printf_float	IMPORT
_exit	IMPORT
_isalnum	IMPORT
_isalpha	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_itoa10	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_qsort	IMPORT
_rand	IMPORT
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_strcspn	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strpbrk	IMPORT
_strrchr	IMPORT
_strspn	IMPORT
_strstr	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_utoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_zerodw	IMPORT
_strtok	EXPORT


*******************************************************************************

* FUNCTION strtok(): defined at strtok.c:5
_strtok	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: str: char *: line 5
*      6,U:    2 bytes: delim: const char *: line 5
* Line strtok.c:9: if
* optim: stripOpToDeadReg
* optim: stripOpToDeadReg
* Emitted no code to cast `int' to `void *'
* PSHS B,A optim: optimizeStackOperations1
	LDD	4,U		variable `str', declared at strtok.c:5
* optim: loadCmpZeroBeqOrBne
	BEQ	L00079		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00078 removed
* Line strtok.c:10
* Line strtok.c:10: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	4,U
	STD	.local.static.strtok.currentString+0,PCR
	BRA	L00080		jump over else clause
L00079	EQU	*		else clause of if() started at strtok.c:9
* Line strtok.c:14
* Line strtok.c:11: if
* optim: stripOpToDeadReg
* optim: stripOpToDeadReg
* Emitted no code to cast `int' to `void *'
* PSHS B,A optim: optimizeStackOperations1
	LDD	.local.static.strtok.currentString+0,PCR	variable `currentString', declared at strtok.c:7
* optim: loadCmpZeroBeqOrBne
	BNE	L00082		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00081 removed
* Line strtok.c:12
* Line strtok.c:12: return with value
	CLRA
	CLRB
* Emitted no code to cast `int' to `void *'
* Emitted no code to cast `void *' to `char *'
	BRA	L00077		return (strtok.c:12)
L00082	EQU	*		else clause of if() started at strtok.c:11
* Useless label L00083 removed
L00080	EQU	*		end of if() started at strtok.c:9
* Line strtok.c:14: assignment: =
* Line strtok.c:14: function call: strspn()
	LDD	6,U		variable `delim', declared at strtok.c:5
	PSHS	B,A		argument 2 of strspn(): const char *
	LDD	.local.static.strtok.currentString+0,PCR	variable `currentString', declared at strtok.c:7
	PSHS	B,A		argument 1 of strspn(): char *
	LBSR	_strspn
	LEAS	4,S
	ADDD	.local.static.strtok.currentString+0,PCR	optim: pushDLoadAdd
* 
* 
	STD	4,U
* Line strtok.c:15: assignment: =
* Line strtok.c:15: function call: strcspn()
	LDD	6,U		variable `delim', declared at strtok.c:5
	PSHS	B,A		argument 2 of strcspn(): const char *
	LDD	4,U		variable `str', declared at strtok.c:5
	PSHS	B,A		argument 1 of strcspn(): char *
	LBSR	_strcspn
	LEAS	4,S
	ADDD	4,U		optim: pushDLoadAdd
* 
* 
	STD	.local.static.strtok.currentString+0,PCR
* Line strtok.c:16: if
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
* optim: storeLoad
	CMPD	4,U		optim: optimizeStackOperations4
	BNE	L00085		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00084 removed
* Line strtok.c:17
* Line strtok.c:18: assignment: =
	CLRA
	CLRB
* Emitted no code to cast `int' to `void *'
	STD	.local.static.strtok.currentString+0,PCR
* Line strtok.c:19: return with value
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
* Emitted no code to cast `int' to `void *'
* Emitted no code to cast `void *' to `char *'
	BRA	L00077		return (strtok.c:19)
L00085	EQU	*		else clause of if() started at strtok.c:16
* Useless label L00086 removed
* Line strtok.c:22: if
	LDB	[.local.static.strtok.currentString+0,PCR]	indirection
* optim: loadCmpZeroBeqOrBne
	BEQ	L00088		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00087 removed
* Line strtok.c:23
* Line strtok.c:24: assignment: =
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* optim: optimizeLdx
	LDB	#0		optim: optimizeStackOperations1
	STB	[.local.static.strtok.currentString+0,PCR]	optim: optimizeLdx
* Line strtok.c:25: pre-increment
	LDX	.local.static.strtok.currentString+0,PCR	variable `currentString', declared at strtok.c:25
	LEAX	1,X
	STX	.local.static.strtok.currentString+0,PCR
	BRA	L00089		jump over else clause
L00088	EQU	*		else clause of if() started at strtok.c:22
* Line strtok.c:28
* Line strtok.c:28: assignment: =
	CLRA
	CLRB
* Emitted no code to cast `int' to `void *'
	STD	.local.static.strtok.currentString+0,PCR
L00089	EQU	*		end of if() started at strtok.c:22
* Line strtok.c:30: return with value
	LDD	4,U		variable `str', declared at strtok.c:5
* optim: branchToNextLocation
L00077	EQU	*		end of strtok()
	LEAS	,U
	PULS	U,PC
* END FUNCTION strtok(): defined at strtok.c:5
funcend_strtok	EQU *
funcsize_strtok	EQU	funcend_strtok-_strtok


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables
.local.static.strtok.currentString	EQU	*		currentString: char *: strtok.c:7
	FDB	$00		0 decimal


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 2 utility routine(s).
_strcspn	IMPORT
_strspn	IMPORT


*******************************************************************************

	END
