* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


__FinishIntegerToASCII	IMPORT
___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_bsearch	IMPORT
_cmpdww	IMPORT
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enable_printf_float	IMPORT
_exit	IMPORT
_isalnum	IMPORT
_isalpha	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_itoa10	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_qsort	IMPORT
_rand	IMPORT
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_strcspn	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strpbrk	IMPORT
_strrchr	IMPORT
_strspn	IMPORT
_strstr	IMPORT
_strtok	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_zerodw	IMPORT
_utoa10	EXPORT


*******************************************************************************

* FUNCTION utoa10(): defined at utoa.c:13
_utoa10	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-6,S
* Formal parameter(s):
*      4,U:    2 bytes: value: unsigned int: line 13
*      6,U:    2 bytes: str: char *: line 13
* Local non-static variable(s):
*     -6,U:    2 bytes: next: unsigned int: line 28
*     -4,U:    2 bytes: writer: char *: line 22
*     -2,U:    2 bytes: firstDigit: char *: line 25
* Line utoa.c:15: if
	LDD	4,U		variable `value', declared at utoa.c:13
* optim: loadCmpZeroBeqOrBne
	BNE	L00080		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00079 removed
* Line utoa.c:16
* Line utoa.c:17: assignment: =
* LDB #$30 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* optim: optimizeLdx
	LDB	#48		optim: optimizeStackOperations1
	STB	[6,U]		optim: optimizeLdx
* Line utoa.c:18: assignment: =
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	6,U		get pointer value
* optim: optimizeLeax
	LDB	#0		optim: optimizeStackOperations1
	STB	1,X		optim: optimizeLeax
* Line utoa.c:19: return with value
	LDD	6,U		variable `str', declared at utoa.c:13
	BRA	L00078		return (utoa.c:19)
L00080	EQU	*		else clause of if() started at utoa.c:15
* Useless label L00081 removed
* Line utoa.c:22: init of variable writer
	LDD	6,U		variable `str', declared at utoa.c:13
	STD	-4,U		variable writer
* Line utoa.c:25: init of variable firstDigit
* optim: storeLoad
	STD	-2,U		variable firstDigit
* Line utoa.c:26: while
	BRA	L00083		jump to while condition
L00082	EQU	*		while body
* Line utoa.c:28: init of variable next
	LDD	4,U		variable `value', declared at utoa.c:13
	LBSR	DIV16BY10
	STD	-6,U		variable next
* Line utoa.c:29: assignment: =
* optim: storeLoad
	LBSR	MUL16BY10
	PSHS	B,A
	LDD	4,U		variable `value', declared at utoa.c:13
	SUBD	,S++
* Cast from `unsigned int' to byte: result already in B
* optim: optimizeStackOperations2
* optim: optimizeStackOperations2
	ADDB	#$30		optim: optimizeStackOperations2
* optim: stripExtraPushPullB
	LDX	-4,U		get pointer writer
* optim: optimizePostIncrement
* optim: optimizePostIncrement
	STB	,X+		optim: optimizePostIncrement
* optim: stripExtraPushPullB
	STX	-4,U		optim: optimizePostIncrement
* Line utoa.c:30: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	-6,U
	STD	4,U
L00083	EQU	*		while condition at utoa.c:26
	LDD	4,U		variable value
* optim: removeCMPZeroAfterLDIfBHI (BHI->BNE)
	BNE	L00082
* optim: branchToNextLocation
* Useless label L00084 removed
* Line utoa.c:33: return with value
* Line utoa.c:33: function call: _FinishIntegerToASCII()
	LDD	6,U		variable `str', declared at utoa.c:13
	PSHS	B,A		argument 3 of _FinishIntegerToASCII(): char *
	LDD	-4,U		variable `writer', declared at utoa.c:22
	PSHS	B,A		argument 2 of _FinishIntegerToASCII(): char *
	LDD	-2,U		variable `firstDigit', declared at utoa.c:25
	PSHS	B,A		argument 1 of _FinishIntegerToASCII(): char *
	LBSR	__FinishIntegerToASCII
	LEAS	6,S
* optim: branchToNextLocation
L00078	EQU	*		end of utoa10()
	LEAS	,U
	PULS	U,PC
* END FUNCTION utoa10(): defined at utoa.c:13
funcend_utoa10	EQU *
funcsize_utoa10	EQU	funcend_utoa10-_utoa10


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 3 utility routine(s).
DIV16BY10	IMPORT
MUL16BY10	IMPORT
__FinishIntegerToASCII	IMPORT


*******************************************************************************

	END
